services:
  backend:
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
    ports:
      - "5005:5005" # expose for debugging
    volumes:
      - ./backend:/app # live code mounting

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/yarn.lock:/app/yarn.lock
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/components.json:/app/components.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/eslint.config.mjs:/app/eslint.config.mjs
      - ./frontend/next-env.d.ts:/app/next-env.d.ts
      - /app/node_modules # Preserve container's node_modules
      - /app/.next # Preserve build cache
    environment:
      - API_URL=http://backend:5005
